- name: get docker compose binary
  get_url:
    url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: "0755"

- name: Make Docker Compose executable
  file:
    path: /usr/local/bin/docker-compose
    mode: "0755"

- name: Verify Docker Compose installation
  command: docker-compose --version
